# Generated by Django 3.2.4 on 2021-07-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booked_time',
            field=models.CharField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')], default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.CharField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')], max_length=20),
        ),
    ]
