# Generated by Django 3.2.4 on 2021-07-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointmed', '0004_auto_20210706_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='booked_time',
        ),
    ]
