# Generated by Django 3.2.4 on 2021-07-06 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointmed', '0005_remove_appointments_booked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
